### PR TITLE
rewrite imports and update gx

### PR DESCRIPTION
**Pull request by keks**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Use `QmRWzPoJjoEfhbNNiADWGL4WrTe7vF1ob2fYDcvNgeWuVM` for go-multiaddr, and `QmcJMBXiguCVmFrctxFArU7fBVQHQernaLj8vFmbSv5RyW` for go-libp2p-crypto

**Comment by keks** [comment]
oh, git, please. I'll fix this mess, sorry.

**Comment by whyrusleeping** [comment]
@keks could you update this to use QmRWzPoJjoEfhbNNiADWGL4WrTe7vF1ob2fYDcvNgeWuVM for go-multiaddr?

**Comment by keks** [comment]
I didn't find any multiaddr deps:

```
keks@keks-x220 ~/go/src/github.com/libp2p/go-libp2p-peer$ gx deps                                              
go-log           QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52 1.2.0
go-base58        QmT8rehPR3F6bmwL6zjUN8XpiDBFFpMP2myPdC6ApsWfJf 0.0.0
go-multihash     QmTvWHtHQhkRD33UNzP3NKsUxX2k2oonrgHXYis7wdhCbA 0.1.0
go-ipfs-util     QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1 1.0.0
go-libp2p-crypto QmcJMBXiguCVmFrctxFArU7fBVQHQernaLj8vFmbSv5RyW 1.3.0
```

**Comment by whyrusleeping** [comment]
Oh, thats go-multihash, my bad.

**Comment by whyrusleeping** [comment]
Alright, LGTM, thanks! (and sorry for the delay)

**Comment by keks** [comment]
yeah I could have said that I didn't find it...whatever. Now it's done.

**Pull request merged**
